### ISSUE TITLE
sliderInput not working in shiny with slidify

### ISSUE THREAD

**Issue by datalotpot786** [ramnathv/slidify#445] opened 2015-06-22 22:34 UTC
Ramnath, I was trying to use sliderInput as shiny Input control in my slidify presentation but it appears in the slide as a plain text input box instead of slider. Please let me know if you have some example of sliderInput with shiny/slidify..

Thanks
Sandeep

**Comment by ramnathv** [comment] 2015-06-23 03:45
Please provide reproducible code.

**Comment by datalotpot786** [comment] 2015-06-23 19:13
Ramnath, Please find reproducible code below. There are bunch of issues I have given below. Please let me know what am I doing wrong, thanks.  

1. sliderInput shows only as Text Input
2. ggplot2 and rCharts are not displaying when called as shinyServer plot and chart respectively
3. rCharts without shiny input control also does not display

I have included code from index.Rmd, global.R and server.R files. global.R and server.R files I did keep in my app folder in my slidify directory.

Index.Rmd
---
title       : Title1
subtitle    : Subtitle1
author      : SP
job         :
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      #
widgets     : [interactive, shiny, rCharts,polycharts]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---
 
## Set Data
 
```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
read_chunk('app/global.R');read_chunk('app/server.R')
```
 
 
--- .class #id
 
## ggplot2 with slider Input
 
```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
 
slidifyUI(
  sidebarPanel(
    sliderInput(inputId="freq",label="Frequent Words:",min=3, max=20,value=5,step=2)
  ),
  mainPanel(
    plotOutput('wordfrq')
  )
)
```
 
--- .class #id
 
## ggplot2 with select Input
 
```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
 
slidifyUI(
  sidebarPanel(
    selectInput(inputId="freq",label="Frequent Words:",choices=c(3,5,10,15),selected=5)
  ),
  mainPanel(
    plotOutput('wordfrq')
  )
)
```
 
--- .class #id
 
## rCharts with select Input
 
```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
 
slidifyUI(
  sidebarPanel(
    selectInput(inputId="freq",label="Frequent Words:",choices=c(3,5,10,15),selected=5)
  ),
  mainPanel(
    plotOutput('wordfrq1')
  )
)
```
 
--- &twocol w1:50% w2:50%
 
## ggplot2 & rCharts with no Shiny
 
*** =left
```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
    df1 = head(df,8)
    colourCount = 8
    ggplot(df1, aes(x = reorder(word, -freq), y = freq, ymax=max(freq), fill=word)) +
      geom_bar(stat = 'identity', position=position_dodge(0.7), size=0.3, width=0.3) +
      theme(panel.grid=element_blank()) + theme_grey(base_size = 12) +
      ggtitle("Wordcloud - Most Frequent Words") + theme(plot.title = element_text(lineheight=0.8, size=12, face="bold")) +
      xlab("Word") + ylab("Frequency") + coord_flip() + theme(legend.position='none') #+
    #   #scale_fill_brewer(name='word',type = "seq",  palette = 'Dark2')
    
```
 
*** =right
```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
    df1 = head(df,8)
    colourCount = 8
    rPlot(freq ~ word, color = 'word', type='bar', data =  df1)   
```
 
Global.R
 
library(data.table)
library(ggplot2)
library(scales)
library(dplyr)
 
df <- data.frame(word=c('go','do','to','su','mo','wu','ku','bu','co','no','so','vo','ko','po','du','eu','jo'),
                    freq=c(20,35,55,15,65,80,90,120,230,430,10,12,87,96,180,234,321))
df = arrange(df,-freq)
 
server.R
 
require(rCharts)
require(ggplot2)
library(RColorBrewer)
shinyServer(function(input,output){
  output$wordfrq <- renderPlot({
    df1 = head(df,input$freq)
    colourCount = input$freq
    p1 = ggplot(df1, aes(x = reorder(word, -freq), y = freq, ymax=max(freq), fill=word)) +
      geom_bar(stat = 'identity', position=position_dodge(0.7), size=0.3, width=0.3) +
      theme(panel.grid=element_blank()) + theme_grey(base_size = 12) +
      ggtitle("Wordcloud - Most Frequent Words") + theme(plot.title = element_text(lineheight=0.8, size=12, face="bold")) +
      xlab("Word") + ylab("Frequency") + coord_flip() + theme(legend.position='none') #+
    #   #scale_fill_brewer(name='word',type = "seq",  palette = 'Dark2')
    print(p1)
  })
  output$wordfrq1 <- renderChart({
    df1 = head(df,input$freq)
    colourCount = input$freq
    p1 <- rPlot(freq ~ word, color = 'word', type='bar', data =  df1)
    p1$set(dom = 'wordfrq', width = 300)
    return(p1)
  })
})

**Comment by datalotpot786** [comment] 2015-06-27 14:32
Ramnath, Please let me know if you have any resolution for above code.

**Comment by ramnathv** [comment] 2015-06-27 17:59
You need to use the `runDeck` command from your R console to be able to use shiny controls within a `slidify` presentation. Slidify is undergoing a rewrite at the moment to bring it to be more consistent with how Rmarkdown documents work, so once that gets in, you will be able to knit it in Rstudio.

I will take a closer look at how to make this work right inside RStudio, but it would be a couple of weeks before I can get to that.

**Comment by ramnathv** [comment] 2015-09-05 18:11
Closing this for now. Getting shiny docs working with slidify is more involved and I would rather approach this from scratch rather than patching a hack together.

**Closed by ramnathv** 2015-09-05 18:11 UTC

**Comment by elbamos** [comment] 2017-04-03 23:05
@ramnathv It looks like maybe you've stopped work on this?  Is there any way someone could help and revive the project?
