### ISSUE TITLE
knit: slidify::knit2slides

### ISSUE THREAD

**Issue by marcosci** [ramnathv/slidify#424] opened 2015-05-11 17:43 UTC
Hi @ramnathv ,

in your examples you constantly use the option:
```knit: slidify::knit2slides```

If I use this option, I get the error:

```
Error in if (body$content == "") { : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... %|% -> f -> lapply -> FUN -> apply -> FUN -> parse_body
Execution halted
```

And with
```
output      : slidify::knit2slides
```
i get:
```
Error in dirname(postFile) : 
  argument "inputFile" is missing, with no default
Calls: <Anonymous> ... slidify -> parse_page -> in_dir -> setwd -> dirname
Execution halted
```
R and slidify are both up-to-date. Is there any solution for this problem?

**Comment by ramnathv** [comment] 2015-05-11 20:55
This is a known issue. Duplicate of [https://github.com/ramnathv/slidify/issues/407]. I haven't yet pushed a fix, but am working on it.

**Closed by ramnathv** 2015-05-11 20:55 UTC

**Comment by ramnathv** [comment] 2015-05-12 04:59
See resolution here https://github.com/ramnathv/slidify/issues/407
